### ISSUE TITLE
s/literals/literal/

### ISSUE THREAD

**Issue by atomgalaxy** [ldionne/wg21#3]
https://github.com/ldionne/wg21/blob/397277c02b4a2d7f2f0d02fde0c5cfa68c1f4bc2/p0424.tex#L43

**Comment by ldionne** [comment]
I thought I had already acted on this, but it seems like it went under the radar. Thanks a lot for the correction! However, it seems like it does not apply anymore since the paper was changed significantly for the post-Albuquerque mailing, so I'm closing this.
